### ISSUE TITLE
Unable to find PhotopaySample folder when trying to follow Quick start with the sample app instructions

### ISSUE THREAD

**Issue by suzanneong3** [PhotoPay/photopay-android#1]
Hi guys i am trying to follow the instructions to try the PhotoPay project, i am not sure how to get started as i cant find the PhotopaySample folder.
I also dont understand whats the difference between 'Android Studio integration Using AAR' and 'Quick start with the sample app from the instructions. '
![image](https://user-images.githubusercontent.com/38582609/48240700-b7418680-e40e-11e8-9c9e-670d6facfee4.png)
****

![image](https://user-images.githubusercontent.com/38582609/48240543-1bb01600-e40e-11e8-9d35-7070783af659.png)
![image](https://user-images.githubusercontent.com/38582609/48240581-45693d00-e40e-11e8-94a6-46860c3bf69b.png)

**Comment by DoDoENT** [comment]
Hello!

This repository contains only documentation for the PhotoPay project. In order to get access to the PhotoPay SDK and sample apps, please contact [our sales team](https://microblink.com/contact-us).
